apiVersion: v2
name: limesurvey
type: application
description: Limesurvey is the number one open-source survey software. This chart uses the excellent container image from Adam Zammit of the Australian Consortium for Social and Political Research Incorporated (ACSPRI).
version: 0.3.9
appVersion: "6.7.0"
maintainers:
  - email: christoph.scholz@gmail.com
    name: Christoph Scholz
    url: https://github.com/ChaosKid42
icon: https://raw.githubusercontent.com/area-42/helm-charts/main/charts/limesurvey/icon.png
sources:
  - https://github.com/area-42/helm-charts
  - https://github.com/adamzammit/limesurvey-docker
  - https://limesurvey.org/
dependencies:
  - name: mariadb
    condition: mariadb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ">= 12.x"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update to application version 6.7.0
    - kind: changed
      description: Update to mariadb chart version 20.0.0
